name: colorlight
description: Colorlight Test (via l2ethernet)

publish_to: none

environment:
  sdk: ">=2.16.0  <3.0.0"

dependencies:
  path: ^1.8.1
  l2ethernet: ^0.3.1
  image: ^4.1.7
  args: ^2.3.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.20.1
#  test_utils:
#    path: ../test_utils
