name: colorlight
description: Colorlight Test Driver

publish_to: none

environment:
  sdk: ">=2.16.0  <3.0.0"

ffigen:
  output: 'eth_bindings.dart'
  headers:
    entry-points:
      - 'eth_library/sendeth.h'

dependencies:
  ffi: ^1.1.2
  path: ^1.8.1

dev_dependencies:
  ffigen: ^4.1.3
  lints: ^1.0.1
  test: ^1.20.1
#  test_utils:
#    path: ../test_utils
